### ISSUE TITLE
cesium ion plugin can not be working on version 3.36

### ISSUE THREAD

**Issue by sendreams** [north-road/cesium-ion-plugin#4]
while installed cesium ion plugin, show the error "TypeError: invalid result from CesiumIonDataItemProvider.capabilities(), int cannot be converted to qgis._core.DataItemProviderCapabilities in this context".

Steps to reproduce the issue
1、plugin - install plugin
2、install "cesium ion " plugin
3、 click configration
4、type password
5、show errors

**Comment by sendreams** [comment]
can you please update the release version for qgis store.

**Comment by nyalldawson** [comment]
@sendreams I've just published 1.0.2 with this fix
